// src/assets/categories.js
module.exports = [
    //Pix
    { keyword: 'pix', category: 'Pix' },

    // Alimentação
    { keyword: 'gula', category: 'Alimentação' },
    { keyword: 'supermercado', category: 'Alimentação' },
    { keyword: 'mercado', category: 'Alimentação' },
    { keyword: 'restaurante', category: 'Alimentação' },
    { keyword: 'lanchonete', category: 'Alimentação' },
    { keyword: 'padaria', category: 'Alimentação' },
    { keyword: 'burger', category: 'Alimentação' },
    { keyword: 'pizza', category: 'Alimentação' },
    { keyword: 'sorvete', category: 'Alimentação' },
    { keyword: 'café', category: 'Alimentação' },
    { keyword: 'ifood', category: 'Alimentação' },
    { keyword: 'delivery', category: 'Alimentação' },
    { keyword: 'comida', category: 'Alimentação' },
    { keyword: 'alimentação', category: 'Alimentação' },
    { keyword: 'açougue', category: 'Alimentação' },
    { keyword: 'peixaria', category: 'Alimentação' },
    { keyword: 'hortifruti', category: 'Alimentação' },
    { keyword: 'conveniência', category: 'Alimentação' },
    { keyword: 'fast food', category: 'Alimentação' },
    { keyword: 'food truck', category: 'Alimentação' },
    { keyword: 'buffet', category: 'Alimentação' },
    { keyword: 'churrascaria', category: 'Alimentação' },
    { keyword: 'sushi', category: 'Alimentação' },
    { keyword: 'pastelaria', category: 'Alimentação' },
    { keyword: 'confeitaria', category: 'Alimentação' },
    { keyword: 'cafeteria', category: 'Alimentação' },
    { keyword: 'mcdonalds', category: 'Alimentação' },
    { keyword: 'mc donalds', category: 'Alimentação' },
    { keyword: 'burger king', category: 'Alimentação' },
    { keyword: 'bk', category: 'Alimentação' },
    { keyword: 'subway', category: 'Alimentação' },
    { keyword: 'habibs', category: 'Alimentação' },
    { keyword: 'giraffas', category: 'Alimentação' },
    { keyword: 'bobs', category: 'Alimentação' },
    { keyword: 'bobs burgers', category: 'Alimentação' },
    { keyword: 'spoleto', category: 'Alimentação' },
    { keyword: 'coco bambu', category: 'Alimentação' },
    { keyword: 'outback', category: 'Alimentação' },
    { keyword: 'applebees', category: 'Alimentação' },
    { keyword: 'apple bees', category: 'Alimentação' },
    { keyword: 'pizza hut', category: 'Alimentação' },
    { keyword: 'dominos', category: 'Alimentação' },
    { keyword: 'domino\'s pizza', category: 'Alimentação' },
    { keyword: 'casa do pão de queijo', category: 'Alimentação' },
    { keyword: 'casa do pão', category: 'Alimentação' },
    { keyword: 'kfc', category: 'Alimentação' },
    { keyword: 'kentucky fried chicken', category: 'Alimentação' },
    { keyword: 'taco bell', category: 'Alimentação' },
    { keyword: 'starbucks', category: 'Alimentação' },
    { keyword: 'burger', category: 'Alimentação' },
    { keyword: 'fast food', category: 'Alimentação' },
    { keyword: 'lanche', category: 'Alimentação' },
    { keyword: 'lanchonete', category: 'Alimentação' },
    { keyword: 'hamburgueria', category: 'Alimentação' },
    { keyword: 'pizzaria', category: 'Alimentação' },
    { keyword: 'sanduíche', category: 'Alimentação' },
    { keyword: 'sanduiche', category: 'Alimentação' },
    { keyword: 'batata frita', category: 'Alimentação' },
    { keyword: 'refrigerante', category: 'Alimentação' },
    { keyword: 'sorvete', category: 'Alimentação' },
    { keyword: 'milkshake', category: 'Alimentação' },
    { keyword: 'açaí', category: 'Alimentação' },
    { keyword: 'crepe', category: 'Alimentação' },
    { keyword: 'hot dog', category: 'Alimentação' },
    { keyword: 'cachorro quente', category: 'Alimentação' },
    { keyword: 'sushi', category: 'Alimentação' },
    { keyword: 'japa', category: 'Alimentação' },
    { keyword: 'japanese food', category: 'Alimentação' },
    { keyword: 'comida japonesa', category: 'Alimentação' },
    { keyword: 'comida rápida', category: 'Alimentação' },
    { keyword: 'fast casual', category: 'Alimentação' },
    { keyword: 'popeyes', category: 'Alimentação' },
  
    // Transporte
    { keyword: 'posto', category: 'Transporte' },
    { keyword: 'pao', category: 'Transporte' },
    { keyword: 'combustível', category: 'Transporte' },
    { keyword: 'gasolina', category: 'Transporte' },
    { keyword: 'etanol', category: 'Transporte' },
    { keyword: 'diesel', category: 'Transporte' },
    { keyword: 'uber', category: 'Transporte' },
    { keyword: '99', category: 'Transporte' },
    { keyword: 'taxi', category: 'Transporte' },
    { keyword: 'estacionamento', category: 'Transporte' },
    { keyword: 'pedágio', category: 'Transporte' },
    { keyword: 'transporte', category: 'Transporte' },
    { keyword: 'ônibus', category: 'Transporte' },
    { keyword: 'metrô', category: 'Transporte' },
    { keyword: 'trem', category: 'Transporte' },
    { keyword: 'bilhete único', category: 'Transporte' },
    { keyword: 'aplicativo de transporte', category: 'Transporte' },
    { keyword: 'aluguel de carro', category: 'Transporte' },
    { keyword: 'lavagem de carro', category: 'Transporte' },
    { keyword: 'mecânico', category: 'Transporte' },
    { keyword: 'auto elétrica', category: 'Transporte' },
    { keyword: 'pneus', category: 'Transporte' },
    { keyword: 'revisão', category: 'Transporte' },
    { keyword: 'seguro de carro', category: 'Transporte' },
    { keyword: 'pão de açúcar', category: 'Alimentação' },
    { keyword: 'extra', category: 'Alimentação' },
    { keyword: 'carrefour', category: 'Alimentação' },
    { keyword: 'atacadão', category: 'Alimentação' },
    { keyword: 'assai', category: 'Alimentação' },
    { keyword: 'big', category: 'Alimentação' },
    { keyword: 'compre bem', category: 'Alimentação' },
    { keyword: 'bom preço', category: 'Alimentação' },
    { keyword: 'tododia', category: 'Alimentação' },
    { keyword: 'walmart', category: 'Alimentação' },
    { keyword: 'zaffari', category: 'Alimentação' },
    { keyword: 'bourbon', category: 'Alimentação' },
    { keyword: 'muffato', category: 'Alimentação' },
    { keyword: 'pereira', category: 'Alimentação' },
    { keyword: 'mateus', category: 'Alimentação' },
    { keyword: 'supermercados bh', category: 'Alimentação' },
    { keyword: 'guanabara', category: 'Alimentação' },
    { keyword: 'festval', category: 'Alimentação' },
    { keyword: 'lopes', category: 'Alimentação' },
    { keyword: 'condor', category: 'Alimentação' },
    { keyword: 'savegnago', category: 'Alimentação' },
    { keyword: 'prezunic', category: 'Alimentação' },
    { keyword: 'sonda', category: 'Alimentação' },
    { keyword: 'rede economia', category: 'Alimentação' },
    { keyword: 'super nosso', category: 'Alimentação' },
    { keyword: 'g barbosa', category: 'Alimentação' },
    { keyword: 'jacomar', category: 'Alimentação' },

    // Saúde
    { keyword: 'drogasil', category: 'Saúde' },
    { keyword: 'droga sil', category: 'Saúde' },
    { keyword: 'drogaria são paulo', category: 'Saúde' },
    { keyword: 'drogaria sp', category: 'Saúde' },
    { keyword: 'drogaria pacheco', category: 'Saúde' },
    { keyword: 'pague menos', category: 'Saúde' },
    { keyword: 'drogaria pague menos', category: 'Saúde' },
    { keyword: 'drogaria araujo', category: 'Saúde' },
    { keyword: 'araujo', category: 'Saúde' },
    { keyword: 'drogaria raia', category: 'Saúde' },
    { keyword: 'raia', category: 'Saúde' },
    { keyword: 'drogaria farmasil', category: 'Saúde' },
    { keyword: 'farmasil', category: 'Saúde' },
    { keyword: 'drogaria extra', category: 'Saúde' },
    { keyword: 'drogaria farmácia', category: 'Saúde' },
    { keyword: 'farmácia', category: 'Saúde' },
    { keyword: 'farmacia', category: 'Saúde' },
    { keyword: 'drogaria', category: 'Saúde' },
    { keyword: 'droga', category: 'Saúde' },
    { keyword: 'drogaria popular', category: 'Saúde' },
    { keyword: 'drogaria santos', category: 'Saúde' },
    { keyword: 'drogaria santo antônio', category: 'Saúde' },
    { keyword: 'drogaria nissei', category: 'Saúde' },
    { keyword: 'drogaria rossi', category: 'Saúde' },
    { keyword: 'drogaria di', category: 'Saúde' },
    { keyword: 'drogaria farmácia popular', category: 'Saúde' },
    { keyword: 'farmácia popular', category: 'Saúde' },
    { keyword: 'farmacia popular', category: 'Saúde' },
    { keyword: 'drogaria farmácia econômica', category: 'Saúde' },
    { keyword: 'farmácia econômica', category: 'Saúde' },
    { keyword: 'farmacia economica', category: 'Saúde' },
    { keyword: 'drogaria farmácia barata', category: 'Saúde' },
    { keyword: 'farmácia barata', category: 'Saúde' },
    { keyword: 'farmacia barata', category: 'Saúde' },
    { keyword: 'drogaria farmácia 24 horas', category: 'Saúde' },
    { keyword: 'farmácia 24 horas', category: 'Saúde' },
    { keyword: 'farmacia 24 horas', category: 'Saúde' },
    { keyword: 'drogaria farmácia de plantão', category: 'Saúde' },
    { keyword: 'farmácia de plantão', category: 'Saúde' },
    { keyword: 'farmacia de plantao', category: 'Saúde' },
    { keyword: 'drogaria farmácia de manipulação', category: 'Saúde' },
    { keyword: 'farmácia de manipulação', category: 'Saúde' },
    { keyword: 'farmacia de manipulacao', category: 'Saúde' },
    { keyword: 'drogaria farmácia online', category: 'Saúde' },
    { keyword: 'farmácia online', category: 'Saúde' },
    { keyword: 'farmacia online', category: 'Saúde' },
    { keyword: 'drogaria farmácia delivery', category: 'Saúde' },
    { keyword: 'farmácia delivery', category: 'Saúde' },
    { keyword: 'farmacia delivery', category: 'Saúde' },
    { keyword: 'nissei', category: 'Saúde' },
    { keyword: 'panvel', category: 'Saúde' },
    { keyword: 'farmácia', category: 'Saúde' },
    { keyword: 'farmacia', category: 'Saúde' },
    { keyword: 'farma', category: 'Saúde' },
    { keyword: 'droga', category: 'Saúde' },
    { keyword: 'drogasil', category: 'Saúde' },
    { keyword: 'drogaria', category: 'Saúde' },
    { keyword: 'hospital', category: 'Saúde' },
    { keyword: 'clínica', category: 'Saúde' },
    { keyword: 'médico', category: 'Saúde' },
    { keyword: 'dentista', category: 'Saúde' },
    { keyword: 'academia', category: 'Saúde' },
    { keyword: 'suplemento', category: 'Saúde' },
    { keyword: 'plano de saúde', category: 'Saúde' },
    { keyword: 'consulta', category: 'Saúde' },
    { keyword: 'exame', category: 'Saúde' },
    { keyword: 'laboratório', category: 'Saúde' },
    { keyword: 'ótica', category: 'Saúde' },
    { keyword: 'psicólogo', category: 'Saúde' },
    { keyword: 'fisioterapeuta', category: 'Saúde' },
    { keyword: 'nutricionista', category: 'Saúde' },
    { keyword: 'medicamento', category: 'Saúde' },
    { keyword: 'remédio', category: 'Saúde' },
    { keyword: 'saúde', category: 'Saúde' },
    { keyword: 'bem-estar', category: 'Saúde' },
    { keyword: 'spa', category: 'Saúde' },
    { keyword: 'massagem', category: 'Saúde' },
    { keyword: 'pilates', category: 'Saúde' },
    { keyword: 'yoga', category: 'Saúde' },
    { keyword: 'amil', category: 'Saúde' },
    { keyword: 'amil saúde', category: 'Saúde' },
    { keyword: 'unimed', category: 'Saúde' },
    { keyword: 'unimed saúde', category: 'Saúde' },
    { keyword: 'sulamérica', category: 'Saúde' },
    { keyword: 'sulamerica saúde', category: 'Saúde' },
    { keyword: 'bradesco saúde', category: 'Saúde' },
    { keyword: 'bradesco seguros', category: 'Saúde' },
    { keyword: 'hapvida', category: 'Saúde' },
    { keyword: 'hapvida saúde', category: 'Saúde' },
    { keyword: 'notre dame intermédica', category: 'Saúde' },
    { keyword: 'notredame intermédica', category: 'Saúde' },
    { keyword: 'notre dame', category: 'Saúde' },
    { keyword: 'intermédica', category: 'Saúde' },
    { keyword: 'prevent senior', category: 'Saúde' },
    { keyword: 'prevent sênior', category: 'Saúde' },
    { keyword: 'prevent', category: 'Saúde' },
    { keyword: 'são cristóvão saúde', category: 'Saúde' },
    { keyword: 'são cristóvão', category: 'Saúde' },
    { keyword: 'cassi', category: 'Saúde' },
    { keyword: 'cassi saúde', category: 'Saúde' },
    { keyword: 'geap', category: 'Saúde' },
    { keyword: 'geap saúde', category: 'Saúde' },
    { keyword: 'amil dental', category: 'Saúde' },
    { keyword: 'unimed dental', category: 'Saúde' },
    { keyword: 'odontoprev', category: 'Saúde' },
    { keyword: 'odontoprev saúde', category: 'Saúde' },
    { keyword: 'sulamerica dental', category: 'Saúde' },
    { keyword: 'bradesco dental', category: 'Saúde' },
    { keyword: 'hapvida dental', category: 'Saúde' },
    { keyword: 'plano de saúde', category: 'Saúde' },
    { keyword: 'plano saúde', category: 'Saúde' },
    { keyword: 'seguro saúde', category: 'Saúde' },
    { keyword: 'operadora de saúde', category: 'Saúde' },
  
    // Lazer
    { keyword: 'cinema', category: 'Lazer' },
    { keyword: 'netflix', category: 'Lazer' },
    { keyword: 'spotify', category: 'Lazer' },
    { keyword: 'parque', category: 'Lazer' },
    { keyword: 'shopping', category: 'Lazer' },
    { keyword: 'viagem', category: 'Lazer' },
    { keyword: 'hotel', category: 'Lazer' },
    { keyword: 'passagem', category: 'Lazer' },
    { keyword: 'teatro', category: 'Lazer' },
    { keyword: 'show', category: 'Lazer' },
    { keyword: 'festa', category: 'Lazer' },
    { keyword: 'evento', category: 'Lazer' },
    { keyword: 'museu', category: 'Lazer' },
    { keyword: 'exposição', category: 'Lazer' },
    { keyword: 'parque de diversões', category: 'Lazer' },
    { keyword: 'zoológico', category: 'Lazer' },
    { keyword: 'aquário', category: 'Lazer' },
    { keyword: 'jogos', category: 'Lazer' },
    { keyword: 'videogame', category: 'Lazer' },
    { keyword: 'livraria', category: 'Lazer' },
    { keyword: 'hobby', category: 'Lazer' },
    { keyword: 'esporte', category: 'Lazer' },
    { keyword: 'futebol', category: 'Lazer' },
    { keyword: 'piscina', category: 'Lazer' },
    { keyword: 'clube', category: 'Lazer' },
    { keyword: 'bar', category: 'Lazer' },
  
    // Educação
    { keyword: 'livraria', category: 'Educação' },
    { keyword: 'curso', category: 'Educação' },
    { keyword: 'escola', category: 'Educação' },
    { keyword: 'faculdade', category: 'Educação' },
    { keyword: 'material escolar', category: 'Educação' },
    { keyword: 'universidade', category: 'Educação' },
    { keyword: 'aula', category: 'Educação' },
    { keyword: 'professor', category: 'Educação' },
    { keyword: 'livro', category: 'Educação' },
    { keyword: 'apostila', category: 'Educação' },
    { keyword: 'ensino', category: 'Educação' },
    { keyword: 'educação', category: 'Educação' },
    { keyword: 'idiomas', category: 'Educação' },
    { keyword: 'inglês', category: 'Educação' },
    { keyword: 'espanhol', category: 'Educação' },
    { keyword: 'francês', category: 'Educação' },
    { keyword: 'workshop', category: 'Educação' },
    { keyword: 'seminário', category: 'Educação' },
    { keyword: 'palestra', category: 'Educação' },
    { keyword: 'treinamento', category: 'Educação' },
    { keyword: 'capacitação', category: 'Educação' },
    { keyword: 'pesquisa', category: 'Educação' },
    { keyword: 'biblioteca', category: 'Educação' },
  
    // Compras
    { keyword: 'e-commerce', category: 'Compras' },
    { keyword: 'americanas', category: 'Compras' },
    { keyword: 'amazon', category: 'Compras' },
    { keyword: 'shopee', category: 'Compras' },
    { keyword: 'mercado livre', category: 'Compras' },
    { keyword: 'loja', category: 'Compras' },
    { keyword: 'vestuário', category: 'Compras' },
    { keyword: 'eletrônico', category: 'Compras' },
    { keyword: 'celular', category: 'Compras' },
    { keyword: 'computador', category: 'Compras' },
    { keyword: 'tablet', category: 'Compras' },
    { keyword: 'roupa', category: 'Compras' },
    { keyword: 'sapato', category: 'Compras' },
    { keyword: 'acessório', category: 'Compras' },
    { keyword: 'bijuteria', category: 'Compras' },
    { keyword: 'joalheria', category: 'Compras' },
    { keyword: 'presente', category: 'Compras' },
    { keyword: 'brinquedo', category: 'Compras' },
    { keyword: 'decoração', category: 'Compras' },
    { keyword: 'móveis', category: 'Compras' },
    { keyword: 'eletrodoméstico', category: 'Compras' },
    { keyword: 'ferramenta', category: 'Compras' },
    { keyword: 'construção', category: 'Compras' },
    { keyword: 'material de construção', category: 'Compras' },
    { keyword: 'jardinagem', category: 'Compras' },
    { keyword: 'petshop', category: 'Compras' },

    { keyword: 'outros', category: 'Outros' },

    { keyword: 'aplicacao', category: 'Investimento' },
    { keyword: 'aplicação', category: 'Investimento' },
    { keyword: 'tesouro', category: 'Investimento' },
    
    { keyword: 'boleto', category: 'Boleto' },
  ];